### PR TITLE
How to: Write a driver

### PR DESCRIPTION
**Pull request by mghill**
Pulled straight from https://github.com/PlaceOS/drivers/blob/master/docs/writing-a-driver.md

Passed some edits & reformatting plus orthograph-err assisted proofreading.

### CODE REVIEW

**Comment by mghill** [comment]
@kimburgess the codeblocks flagged with crystal don't seem to have highlighting in the way I'd expect (they did in vscode preview but I guess we can use `ruby` tags?)

Not sure if this is related to the font/scheme changes that pushed recently

Edit after some testing: Ruby also doesn't highlight, but java, py etc do. Possibly just not supported? Not sure what the best/closest would be. Or what a fix would look like.

**Comment by kimburgess** [comment]
Nice catch! Added in some support for that via placeos/docs-site@54de69ed27aa6739359274f0d043edfeb6c89ec1.

**Comment by kimburgess** [comment]
And again, sans typo: placeos/docs-site@1da091e.

**Comment by jeremyw24** [comment]
Approved for merge.

**Pull request merged**
