### PR TITLE
Recommended hardware

### LINKED ISSUE #15: Migrated Recommended Hardware Page
Add recommended hardware page from confluence to docs: https://acaprojects.atlassian.net/wiki/spaces/SD/pages/73924609/Recommended+Hardware

### PR DESCRIPTION
**Pull request by mghill**
Now that most of the process is down from going over the key-concepts PR, I'll start marshaling other content in PRs as it gets to a similar level. If it's preferable to get a version of the site up with just basic content, these can simply be held until it's ready.

### CODE REVIEW

**Comment by mghill** [comment]
Odd to note that spelling check didn't pull up the readme.md "issues" (not part of this PR) as it did in #22

**Comment by kimburgess** [comment]
That will be due to this having branches from `master` rather than `key-concepts` (which has the updated config currently). Once that merges in, proofreading will be a little more consistent.

**Comment by mghill** [comment]
Further on the spelling issues - I don't think it's necessarily worth adding each and every model name & number to the linter, but I also can't think of a (regex etc) way to filter out model numbers/non-word names without skipping legitimate typos (especially as some of them *are* intentionally misspelled words. Ugh). 
Also not crash hot on the idea of leaving it so that these errors will be picked up by the checks in all future PRs. Thoughts? 
- We could omit specific docs from future checks
- Could just have a ticker of standard/known numbers of "errors"
- Could create some sort of very extensive allow/skip list in the linter

Not great options

**Comment by mghill** [comment]
Updated in line with both #26 and #27 to use `<i>` around models/brands (plus adding common ones to the linter) and to refactor the tabs feature as Details.

**Comment by kimburgess** [comment]
@mghill the history of this branch and associated change set is a bit wild. Might be worth a prune (or placing the intended doc state onto a fresh branch from master) before looking at merging.

**Comment by mghill** [comment]
Yep, absolute mess. Creating #35 and closing this PR & branch

**Pull request closed without merging**
