### PR TITLE
Aws fargate

### LINKED ISSUE #14: AWS Fargate Deployment Docs
Add AWS Fargate Deployment Docs from Deploy Repo to PlaceOS Documentation Site: 
https://github.com/PlaceOS/deploy-aws/blob/modular/README.md
https://github.com/PlaceOS/deploy-aws/blob/nested/README.md

### PR DESCRIPTION
**Pull request by mghill**
Rebased onto master so it supports auto deployment. Still needs substantial rewriting & some restructuring, but it's together enough to track in a PR.

### CODE REVIEW

**Comment by mghill** [comment]
Any review is welcome, I'll merge this in tomorrow morning

**Comment by jeremyw24** [comment]
@mghill suggest it might be best to nest this i.e How To > Deploy > AWS as we will have Deploy > Azure, Deploy > Kubernetes, Deploy > OpenShift etc. moving forward.

**Comment by mghill** [comment]
> @mghill suggest it might be best to nest this i.e How To > Deploy > AWS as we will have Deploy > Azure, Deploy > Kubernetes, Deploy > OpenShift etc. moving forward.

My understanding (@kimburgess confirm?) That any sidebar menu nesting is happening post the docs site upgrade to alpha.74 where there is a better way to do it. 

My intent is to put it all in as is (buckets aren't that big/messy for mvp) and then sort the sidebar after. There will be no effect on the URLs

**Comment by kimburgess** [comment]
Yep - for initial content build treat paths as immutable (ideally), but menu structure as dynamic. Important thing is to ensure links always remain valid. How visitors discover this content is something that's safe(r) to shuffle.

**Pull request merged**
