### PR TITLE
Recommended products

### LINKED ISSUE #15: Migrated Recommended Hardware Page
Add recommended hardware page from confluence to docs: https://acaprojects.atlassian.net/wiki/spaces/SD/pages/73924609/Recommended+Hardware

### PR DESCRIPTION
**Pull request by mghill**
#25 was a mess, this is clean and accurately named

### CODE REVIEW

**Comment by kimburgess** [comment]
It may be better to restructure where this information sits:
- Hosting environments are tightly tied to deployment info. Likewise, OS'es are related to hosting environments (in some cases the OS may be completely obfuscated, for example when deploying to a managed Kubernetes service).
- Label printers are a device that integrates exactly the same as every other device and service (drivers).

This then leaves the UI devices and MDM platforms for these. Building a resource specific to that set of recommendations seems to be a neatly separated bit of info not covered elsewhere.

**Comment by mghill** [comment]
>  * Hosting environments are tightly tied to deployment info. Likewise, OS'es are related to hosting environments (in some cases the OS may be completely obfuscated, for example when deploying to a managed Kubernetes service).

It could be worth splitting these off into a separate doc, and docusaurus supports [embedding/concatenating markdown docs](https://v2.docusaurus.io/examples/markdownpageexample/#import-mdx-and-md-files). So if these were peeled off, they could then be embedded back into this page as well as wherever else they would be needed (such as in deployment guides/specs). Gives good version control, but gets a bit into conflating structure and content.

>   * Label printers are a device that integrates exactly the same as every other device and service (drivers).

This one seemed weird to me but I assumed that there was a good reason for it to be here. I have no idea what actual significance this would hold, but it was the only peripheral that was included in the old doco. Can check with Steve(or whoever wrote it) and probably wipe it

> This then leaves the UI devices and MDM platforms for these. Building a resource specific to that set of recommendations seems to be a neatly separated bit of info not covered elsewhere.

Yeah those seem like the actual main point of this page, and there's probably more associated info that would get rolled in with them, but when it comes up it can go in here, or an associated page.

**Comment by kimburgess** [comment]
Purely personal opinion, but linking > embedding. Even if it's the same info, this keeps information available at one canonical URI, also also means we avoid mixing MDX into the doc content.

If this content was sourced from an internal doc, the origin of that label printer is likely due to it being specific to a project using that functionality.

What about shuffling this so that we have a `/recommended-hardware/` base path with an initial entry of `user-interfaces`, then can expand from there.

**Comment by mghill** [comment]
If we go ahead with linking, I think it would make sense if we structurally to trend towards more & shorter pages, rather than fewer but comprehensive ones. It's a bit of a different approach, but if everything is interlinked well enough & there is good navigation through the sidebar & folder structure (possibly several tiers) etc, then it should work out. 

My gut leant towards having info viewable all in one place, even if it's drawn from a myriad of files, and even if those files can be displayed in several different places & ways. But I definitely see the benefits with regard to keeping presentation and content separate. It matches how Key Concepts is put together, too and so long as navigation is intuitive then it could be more easily consumed. Will look at any of the docs I'm working on and see if splitting is more appropriate.

**Comment by kimburgess** [comment]
The primary reason for my advocacy against embedding is that it introduces syntax specific to the site render into the docs content. This will make it more complex to make the same content available in contexts outside of the docs site.

I don't think there is a need for this to impact any individual docs length or structure. Any heading used within a doc automatically creates a named anchor which can become the target of any links. This works equally well directly in GitHub as well as the docs site.

For example, from the root a relative link to [`key-concepts/modules.md#purpose`](https://github.com/PlaceOS/docs/blob/master/key-concepts/modules.md#purpose) will work directly. When rendered this will rewrite to [`key-concepts/modules#purpose`](https://docs.placeos.vercel.app/key-concepts/modules#purpose).

**Review by kimburgess — DISMISSED** [review]
@mghill coming back to my [initial comment](https://github.com/PlaceOS/docs/pull/35#issuecomment-745636272) on this PR. The URL structure that this creates is perhaps not the best representation of the content.

I've popped open #45 to define this more generally first, then can integrate decisions there back into this before merge.

**Comment by mghill** [comment]
Very legitimate to not start pushing things into new structures until we're sure about what those structures look like. Further comments on #45

**Comment by jeremyw24** [comment]
Approved for merge.

**Pull request merged**
