### PR TITLE
Deploy a Frontend Interface

### PR DESCRIPTION
**Pull request by jeremyw24**
Guide to deploy a front end interface on PlaceOS.

### CODE REVIEW

**Comment by kimburgess** [comment]
Note: image references included in content here are not valid markdown and the reason for failing builds.

Syntax guide here for correct use of inline images: https://www.markdownguide.org/basic-syntax/#images-1.

**Comment by MrYuion** [comment]
I'd fix it if I had push permissions.

**Comment by jeremyw24** [comment]
> I'd fix it if I had push permissions.

@MrYuion try again.

**Comment by MrYuion** [comment]
@jeremyw24, I think you've been committing to the wrong branch.

**Comment by jeremyw24** [comment]
@MrYuion ive been working off this branch for these docs: https://github.com/PlaceOS/docs/tree/frontend-deployments

**Review by MrYuion — APPROVED** [review]
Looks good.

**Pull request merged**
